In [224]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [225]:
dataset17 = pd.read_csv("cbb17.csv")
dataset19 = pd.read_csv("cbb19.csv")

In [226]:
cleaned17 = dataset17.dropna()
cleaned17 = cleaned17[cleaned17.POSTSEASON != "R68"]
#dummies = pd.get_dummies(cleaned17.CONF)
cleaned17 = cleaned17.replace({"R32": 1, "R64": 0, "S16": 2, "E8": 3, "F4": 4, "2ND": 5, "Champions": 6})

cleaned19 = dataset19.dropna()
cleaned19.set_value(49, 'CONF', 'ASun')
cleaned19 = cleaned19[cleaned19.POSTSEASON != "R68"]
#dummies2 = pd.get_dummies(cleaned19.CONF)
cleaned19 = cleaned19.replace({"R32": 1, "R64": 0, "S16": 2, "E8": 3, "F4": 4, "2ND": 5, "Champions": 6})

In [227]:
cleaned17 = cleaned17.drop(["TEAM"], axis=1)
cleaned17 = cleaned17.drop(["CONF"], axis=1)
cleaned17=(cleaned17-cleaned17.mean())/cleaned17.std()
#cleaned17 = cleaned17.join(dummies)
#cleaned17 = cleaned17.drop(["B10"], axis=1)
outputs17 = cleaned17["POSTSEASON"]
cleaned17 = cleaned17.drop(["POSTSEASON"], axis=1)

cleaned19 = cleaned19.drop(["TEAM"], axis=1)
cleaned19 = cleaned19.drop(["CONF"], axis=1)
cleaned19=(cleaned19-cleaned19.mean())/cleaned19.std()
#cleaned19 = cleaned19.join(dummies2)
#cleaned19 = cleaned19.drop(["B10"], axis=1)
outputs19 = cleaned19["POSTSEASON"]
cleaned19 = cleaned19.drop(["POSTSEASON"], axis=1)

In [228]:
regr = linear_model.LinearRegression()
# Train the model using the training sets
regr.fit(cleaned17, outputs17)
# Make predictions using the testing set
ncaa_pred = regr.predict(cleaned19)

In [230]:
print('Coefficients: \n', regr.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(outputs19, ncaa_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(outputs19, ncaa_pred))

Coefficients: 
 [ 0.04859785  1.09441139  0.8337203  -1.3958229  -0.66499277  0.33020085
 -0.09840006  0.20036612 -0.46405435 -0.19940064  0.16932584  0.00248109
  0.29344147 -0.5069798   0.55476548 -0.40841811  0.51516911 -0.00508548
 -0.97694455 -0.49013451]
Mean squared error: 0.41
Coefficient of determination: 0.58


In [231]:
ncaa_pred

array([ 1.54445923,  2.02482352,  1.14207749,  1.54902724,  1.12465527,
        1.54797263,  1.73896914,  1.96211093,  1.8815351 ,  1.28614527,
        1.39217033,  1.33649836,  0.07485024,  0.29985103,  1.55603854,
        0.25139458,  2.3380941 , -0.98104944,  0.07435159,  0.26412485,
       -0.98305591, -0.28494662,  0.35131744,  0.2572159 , -0.24825495,
        0.45488788,  0.26557656, -0.23522755, -0.21092027, -0.62191999,
       -0.3581807 ,  0.1735271 , -0.61261812, -1.17735926, -0.57030704,
        0.04588684, -0.46546473, -0.61804539, -0.05948386, -0.627029  ,
       -0.8637716 , -0.62112423, -0.87349245, -0.12432805,  0.07536756,
       -0.14614364, -1.60581873, -0.16665391,  0.1940484 , -0.51186522,
       -0.66426224, -0.30314983, -2.26019689, -0.5923021 , -0.96957471,
       -0.29143145, -1.09375465, -0.60099274, -0.59194382, -0.53229962,
       -1.34062807, -0.33128874, -1.38249766, -1.28559396])

In [76]:
outputs19

0     3
1     6
2     3
3     2
4     2
5     4
6     3
7     2
8     5
9     3
10    2
11    2
12    2
13    0
14    2
15    1
16    4
17    0
18    0
19    0
20    0
21    1
22    1
23    1
24    0
25    1
26    0
27    0
28    0
29    0
     ..
34    1
35    1
36    1
37    1
38    1
39    0
40    0
41    1
42    0
44    0
46    2
47    0
48    1
49    1
50    1
51    0
52    0
53    0
54    0
55    0
56    0
57    0
58    0
59    0
60    0
61    0
62    0
63    0
64    0
66    0
Name: POSTSEASON, Length: 64, dtype: int64

In [77]:
cleaned19

G   W  ADJOE  ADJDE  BARTHAG  EFG_O  EFG_D   TOR  TORD   ORB   DRB   FTR  \
0   37  33  123.4   89.9   0.9744   59.0   44.2  14.9  19.0  31.5  26.8  35.3   
1   38  35  123.0   89.9   0.9736   55.2   44.7  14.7  17.5  30.4  25.4  29.1   
2   38  32  118.9   89.2   0.9646   53.6   45.0  17.5  19.4  35.6  29.5  33.2   
3   36  29  120.1   91.4   0.9582   52.9   48.9  17.2  18.3  35.3  22.8  30.2   
4   37  30  114.6   85.6   0.9665   51.6   44.1  13.9  18.0  24.7  24.8  27.5   
5   39  32  119.9   91.0   0.9597   55.2   43.9  18.5  14.9  33.9  26.4  33.6   
6   37  30  117.5   89.8   0.9568   53.0   46.6  18.6  17.9  36.8  25.5  41.9   
7   36  31  122.8   95.2   0.9488   55.3   48.1  15.8  18.0  31.6  30.2  33.3   
8   38  31  115.2   85.2   0.9696   53.5   43.0  17.7  22.8  27.4  28.7  32.9   
9   36  26  122.8   94.3   0.9539   53.6   49.0  15.8  18.6  34.5  27.0  29.9   
10  37  33  115.7   90.5   0.9439   52.1   42.5  16.5  18.2  34.4  26.0  31.6   
11  35  28  117.9   96.6   0.9081   51.2   49.9  17.9  20.1  36.7  30.8  37.1   
12  35  26  117.8   93.4   0.9357   55.6   49.0  17.3  21.6  29.6  27.2  31.9   
13  34  25  108.0   87.8   0.9151   49.4   48.2  17.4  22.8  28.3  25.7  30.6   
14  37  29  111.7   90.9   0.9146   50.5   47.2  18.9  20.3  32.8  27.0  35.8   
15  36  26  112.9   92.4   0.9092   52.6   47.8  18.8  18.2  30.1  27.9  32.5   
16  39  30  121.3   95.2   0.9420   54.4   51.7  16.8  24.6  31.6  32.8  30.9   
17  34  23  108.2   88.6   0.9089   51.1   45.2  14.6  17.2  24.5  26.5  27.3   
18  34  23  116.9   96.8   0.8980   54.6   50.3  19.2  19.5  34.7  29.6  32.7   
19  34  24  111.7   95.9   0.8524   53.5   46.3  19.4  16.6  29.4  26.1  35.1   
20  35  23  118.4   96.6   0.9120   54.7   48.4  16.3  18.8  28.3  30.1  30.0   
21  34  23  111.6   93.3   0.8875   51.4   45.9  19.4  14.1  34.1  24.8  32.8   
22  35  32  113.6   95.3   0.8819   53.4   47.3  16.0  20.3  31.7  26.9  32.7   
23  36  26  114.6   98.9   0.8448   53.2   50.4  16.9  18.0  30.3  27.7  34.4   
24  34  20  112.9   93.1   0.9023   50.9   46.7  17.5  16.1  29.1  25.9  34.9   
25  32  30  116.4   97.1   0.8892   57.5   49.9  16.1  19.1  31.8  25.2  27.8   
26  35  28  112.3   93.8   0.8871   49.0   48.6  16.0  20.9  37.4  29.3  37.6   
27  34  29  112.5   95.9   0.8618   53.7   47.7  14.6  19.2  27.2  24.9  40.8   
28  33  25  104.6   87.6   0.8838   50.1   43.5  20.0  23.4  31.0  30.6  35.7   
29  34  20  110.5   94.2   0.8622   49.6   48.1  18.5  23.1  30.2  33.4  36.8   
..  ..  ..    ...    ...      ...    ...    ...   ...   ...   ...   ...   ...   
34  34  20  114.6   99.2   0.8400   51.2   49.1  19.7  18.6  37.9  29.4  32.3   
35  36  27  105.6   93.1   0.8097   52.1   47.5  19.8  24.2  29.1  34.9  34.7   
36  36  20  110.3   91.6   0.8947   49.8   48.1  17.9  22.4  30.6  32.2  29.9   
37  35  23  116.1  100.6   0.8385   52.7   51.5  17.2  18.4  29.8  29.4  42.3   
38  36  22  110.4   96.3   0.8284   48.2   49.5  17.1  16.9  31.4  28.4  41.6   
39  34  20  107.9   96.9   0.7749   49.9   49.6  17.5  19.8  29.5  29.2  34.5   
40  34  22  113.1   96.3   0.8637   53.8   48.9  16.2  16.3  31.2  23.0  29.1   
41  35  20  107.8   93.8   0.8329   50.3   48.3  18.7  18.2  27.6  25.9  33.7   
42  32  27  114.9  101.0   0.8138   57.6   48.7  15.2  16.0  25.3  25.0  28.5   
44  34  23  108.7   97.6   0.7750   50.6   48.5  18.7  19.0  31.7  26.9  43.8   
46  38  25  108.1   91.7   0.8687   52.0   46.4  17.8  20.9  29.6  28.8  29.4   
47  33  30  111.8   98.2   0.8155   54.1   48.9  17.8  19.1  37.0  22.5  34.6   
48  31  28  110.4   98.6   0.7852   54.8   46.5  17.2  19.4  32.0  30.7  33.5   
49  33  29  109.2   99.6   0.7428   55.9   48.9  17.2  20.5  25.2  26.4  26.7   
50  36  31  107.2   97.6   0.7458   51.3   44.1  17.5  16.7  33.7  27.0  28.7   
51  33  27  107.0   98.1   0.7324   52.6   48.7  16.8  19.1  27.3  22.2  35.9   
52  34  23  109.1  102.5   0.6712   56.5   52.1  16.6  16.7  22.7  24.6  34.3   
53  36  23  101.3   95.7   0.6599   

In [57]:
# Load the diabetes dataset
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

# Use only one feature
diabetes_X = diabetes_X[:, np.newaxis, 2]

# Split the data into training/testing sets
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]

# Split the targets into training/testing sets
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]


In [58]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)

In [59]:
diabetes_y_pred

array([ 225.9732401 ,  115.74763374,  163.27610621,  114.73638965,
        120.80385422,  158.21988574,  236.08568105,  121.81509832,
         99.56772822,  123.83758651,  204.73711411,   96.53399594,
        154.17490936,  130.91629517,   83.3878227 ,  171.36605897,
        137.99500384,  137.99500384,  189.56845268,   84.3990668 ])

In [60]:
diabetes_y_test

array([ 233.,   91.,  111.,  152.,  120.,   67.,  310.,   94.,  183.,
         66.,  173.,   72.,   49.,   64.,   48.,  178.,  104.,  132.,
        220.,   57.])

In [61]:
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(diabetes_y_test, diabetes_y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(diabetes_y_test, diabetes_y_pred))

Coefficients: 
 [ 938.23786125]
Mean squared error: 2548.07
Coefficient of determination: 0.47
